### ISSUE TITLE
[FEATURE] - Webhook flag/configuration to automatically add a repo when webhooks are called

### ISSUE THREAD

**Issue by ypereirareis** [ludofleury/satisfy#104]
Hi,

I recently configured a gitlab webhook to automatically start satis builds for my repositories.
But I had to manually add them all once in satis configuration file or with the satisfy GUI.

Could be good to have a flag/param to allow auto add of repositories when webhooks are called.

I can contribute to this if you think it's a good idea.

**[PROPOSAL]**

```yaml
github.add_repo_if_not_exists: [true|false]
github.add_repo_type: [git|svn|vcs|...]
github.add_repo_src: [source|dist]
```

```yaml
gitlab.add_repo_if_not_exists: [true|false]
gitlab.add_repo_type: [git|svn|vcs|...]
gitlab.add_repo_src: [source|dist]
```

```yaml
bitbucket.add_repo_if_not_exists: [true|false]
bitbucket.add_repo_type: [git|svn|vcs|...]
bitbucket.add_repo_src: [source|dist]
```
