### ISSUE TITLE
Build command doesn't seem to use parameters yml

### ISSUE THREAD

**Issue by mlambley** [ludofleury/satisfy#108]
Good day,

My `parameters.yml` looks like the following:
```yml
parameters:
    secret: <secret>
    satis_filename: '%kernel.project_dir%/app/config/satis.json'
    satis_log_path: '%kernel.project_dir%/var/satis'
    admin.auth: true
    admin.users: <working fine>
    composer.home: '%kernel.project_dir%/var/composer'
    github.secret: <secret>
    gitlab.secret: null
    gitlab.auto_add_repo: false
    gitlab.auto_add_repo_type: null
```

Whenever I run `bin/satis build` I get:
```
File not found: ./satis.json
```

It works when I run `bin/satis build app/config/satis.json`. Given that the `Build Packages` link runs this command, should I just modify the `SatisBuildRunner` file myself, or should the command default to the parameters as specified in `parameters.yml`.

Thank you.
