### ISSUE TITLE
Gitlab webhook BadRequestHttpException: "Invalid Token"

### ISSUE THREAD

**Issue by bmiro** [ludofleury/satisfy#119]
First of all, thanks for the the project! :)

To use it with many repositories I'm trying to configure the gitlab webhook with auto_add.

I'm using satisfy 3.2 and GitLab CE 12.6.4.

I've adjusted the `app/config/parameteres.yml` to look like this:

```
parameters:
    secret: <some secret>
    satis_filename: '%kernel.project_dir%/satis.json'
    satis_log_path: '%kernel.project_dir%/var/satis'
    admin.auth: true
    admin.users:
        -
            name: admin
            password: <secret>
            roles: ['ROLE_ADMIN']
    composer.home: '%kernel.project_dir%/var/composer'
    github.secret: null
    gitlab.secret: 8f8f9*******token-secret**********60e2
    gitlab.auto_add_repo: true
    gitlab.auto_add_repo_type: git
```
And also setled the same `gitlab.secret` at the Gitlab Webhook as `Secret Token`

![gitlab-wh](https://user-images.githubusercontent.com/398519/73007240-82033780-3e0c-11ea-8e6f-c35534865fd1.png)

But it isn't working reporting `BadRequestHttpException: "Invalid Token"`
```
fpm_1     | [23-Jan-2020 17:10:48] WARNING: [pool app0001] child 45 said into stderr: "2020-01-23T17:10:48+00:00 [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Invalid Token" at src/Playbloom/Satisfy/Webhook/AbstractWebhook.php line 42"
```
I've didn't found many documentation and don't know if I'm missing something.

With those versions is it supposed to work?
