### ISSUE TITLE
Add documentation for parameters.yml

### ISSUE THREAD

**Issue by robrecord** [ludofleury/satisfy#142]
I'm having a headache setting this up because there is no documentation for the parameters config file.

I've worked out that I need to add users in the following format:

```
  admin.auth: true
  admin.users:
    myusername:
      password: mypassword
      roles: 'ROLE_ADMIN'
```

Could this file be documented?

I don't know what 'secret' does, and I'm not sure if my github secret works because I see no output on the build. (This could be another issue though).
