### ISSUE TITLE
GitHub Webhook URL returns 400 error when APP_DEBUG is 0

### ISSUE THREAD

**Issue by ihor-sviziev** [ludofleury/satisfy#173]
Hi,

I noticed that Satisfy returns a 400 error when APP_MODE=prod and APP_DEBUG=0. When switching APP_DEBUG to 1 - it works fine.
I don't see any logs, so it's hard to understand why it happened.
Any thoughts?

**Comment by ramunasd** [comment]
HTTP error code 400 means "Bad request". It is expected to get such response if request is not valid.
With debug mode on you get nice error page with stack trace and other info.

The latest master has monolog logger installed. Please upgrade and check /var/log/* for errors. If there is any, then please report as another issue.

**Comment by ihor-sviziev** [comment]
Thx for the fix. Can check it in a week

**Comment by ihor-sviziev** [comment]
Hi @ramunasd,
Just now was able to test your change - it works fine. Thank you for the fix.

**Comment by ihor-sviziev** [comment]
@ramunasd, just after the upgrade to the latest version, Satisfy stopped automatically adding new repositories using the webhook from GitHub. Can it be related to these changes you did recently?

**Comment by ramunasd** [comment]
Please make sure your parameters are correct

**Comment by ihor-sviziev** [comment]
I checked, and for some reason, the `github.auto_add_repo` and `github.auto_add_repo_type` got lost during the update. So I added them back, restarted the web server, and still the same error and the message. 
Could you please point me out what could be wrong?
Here is my parameters.yml file:
```
# This file is auto-generated during the composer install
parameters:
    secret: "my_own_secret"
    satis_filename: '%kernel.project_dir%/satis.json'
    satis_log_path: '%kernel.project_dir%/var/satis'
    admin.auth: false
    admin.users: {  }
    composer.home: '%kernel.project_dir%/var/composer'
    github.secret: "my_github_secret"
    github.auto_add_repo: true
    github.auto_add_repo_type: "github"
```
