### ISSUE TITLE
How to configure the login 

### ISSUE THREAD

**Issue by oskarcalvo** [ludofleury/satisfy#96]
Hello, I'm trying to follow the documentation to add an administration password to Satisfy, but I get this error:

```php
{       
   if (!$this->getParameter('admin.auth'))  {            return;        }        
   parent::denyAccessUnlessGranted('ROLE_ADMIN');    
}
```

this is the configuration

```yml
parameters:
    secret: secret
    satis_filename: '%kernel.project_dir%/satis.json'
    satis_log_path: '%kernel.project_dir%/var/satis'
    admin.auth: true
    admin.users:
        -
            name: admin
            password: password
    composer.home: '%kernel.project_dir%/var/composer'
    github.secret: null
```
